language: python
env:
  global:
  - secure: pHG7NFeJc33eOhZTbLlmLQb0kx1wdOg+NLIMMwFIuMMJNy2JYwRYEvkQvvMmMHKF+e3HocxOKDoLTV0qqSIZuDEA5ByXaNvYuW1wU70NUE99+tQPy8jpfB6gCGrACC7KFe6wbD4YtwG2VMrEZfR6ElbVhGDHc0pC1Tw7MbEq/ASPXUdEt6ZqFzIhroGvSGoiW3JfurVLsn71/bC1ZDcg/Rd5WFV54cuW0vSP9TVD405+R2xeOCUwW+6QuE29hCHyIcgWZjPe31QYN5yBeJZgD0yK2sa6x/RY4pvxEx01i7tEcfikjJtEE6tw7AZcr/yBDP3HZXAn1430u179subr+u/gi7x4bnzLitviJvWteIVNcjssr4wPd2EqCmd8wEwrSn2LwcfxxZfbyutEIs+9D0m1faRlcpmUMIuhynpntXer2F74DhHVr0xyXQMhVXA0vuBrAC96qtwCbmjPGuAkC4bX/jlMck9hyuZXya2O4bULG8em9S5VUdpx6+X9cjE/Z5hoJpCd9FPFvtYIYX2u/m1q9BnfpHZHU7jA32BvBw5vPCqVRz7Y0i3EVtXFt68aWS+1B5O/2/6MrsAVw3D8OH2gzjG3tW10nAWAZu0u51YpHsALZWGM4ijf9e8J3HxY5mtVNXz4qmW/nW9bWCZo5pcbUKvhVzhejhjDvpRzU1g=
addons:
  apt:
    packages:
    - zsh
    - csh
    - tcsh
    - posh
    - ksh
  update: true
git:
  depth: 100
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
python:
- 2.7
- 3.4
notifications:
  email: false
before_install:
- export TZ=Europe/Prague
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda2/bin:$PATH
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
install:
- pip install twine
- conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  pandas statsmodels
sudo: required
after_success:
- coveralls --config_file .coveragerc
script:
- python setup.py install
before_deploy:
- python setup.py develop install
- python setup.py sdist
deploy:
  provider: pypi
  user: sanderroosendaal
  password:
    secure: pHG7NFeJc33eOhZTbLlmLQb0kx1wdOg+NLIMMwFIuMMJNy2JYwRYEvkQvvMmMHKF+e3HocxOKDoLTV0qqSIZuDEA5ByXaNvYuW1wU70NUE99+tQPy8jpfB6gCGrACC7KFe6wbD4YtwG2VMrEZfR6ElbVhGDHc0pC1Tw7MbEq/ASPXUdEt6ZqFzIhroGvSGoiW3JfurVLsn71/bC1ZDcg/Rd5WFV54cuW0vSP9TVD405+R2xeOCUwW+6QuE29hCHyIcgWZjPe31QYN5yBeJZgD0yK2sa6x/RY4pvxEx01i7tEcfikjJtEE6tw7AZcr/yBDP3HZXAn1430u179subr+u/gi7x4bnzLitviJvWteIVNcjssr4wPd2EqCmd8wEwrSn2LwcfxxZfbyutEIs+9D0m1faRlcpmUMIuhynpntXer2F74DhHVr0xyXQMhVXA0vuBrAC96qtwCbmjPGuAkC4bX/jlMck9hyuZXya2O4bULG8em9S5VUdpx6+X9cjE/Z5hoJpCd9FPFvtYIYX2u/m1q9BnfpHZHU7jA32BvBw5vPCqVRz7Y0i3EVtXFt68aWS+1B5O/2/6MrsAVw3D8OH2gzjG3tW10nAWAZu0u51YpHsALZWGM4ijf9e8J3HxY5mtVNXz4qmW/nW9bWCZo5pcbUKvhVzhejhjDvpRzU1g=
  distributions: sdist
  on:
    branch: master
    repo: sanderroosendaal/rowingphysics
